version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    container_name: algafood-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - algafood-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "algafood-mysql:3306" ]
      interval: 30s
      timeout: 10s
      retries: 5

  algafood-api:
#    image: algafood-api # isso serve se a image ja tiver contruida
    build: . # constroi em tempo de execucao
    restart: always # rebuilda sempre que tiver alguma atualizacao no diretorio atual
    container_name: algafood-api
    environment:
      DB_HOST: algafood-mysql
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      algafood-mysql:
        condition: service_healthy


#  como iniciar na mao
#  docker run -p 8080:8080 --network rede-test algafood-api
#  docker run -e MYSQL_ROOT_PASSWORD=root --network rede-test -d -p 3306:3306 --name algafood-mysql  mysql:8.0
#  docker run -p 8080:8080 -e DB_HOST=algafood-mysql  --network rede-test algafood-api